### ISSUE TITLE
Merge into official docker-compose file

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda-cloud-docker-compose#1]
This project should be merged into the official docker-compose file of the getting started guide:
https://github.com/camunda-cloud/camunda-cloud-get-started/blob/main/docker-compose.yaml

We have retired https://github.com/camunda-community-hub/zeebe-docker-compose for the same reason.

@menski FYI

**Comment by akeller** [comment]
There is no action I can take here at this time, but the docker-compose experience is something we know needs some work.

**Comment by falko** [comment]
I like the idea of using profiles for optional features that @saig0 introduced in https://github.com/camunda-cloud/camunda-cloud-get-started/pull/79

That could be a way to allow for a single docker-compose file that the community can collaborate on and avoid the need for a repo like this.

**Comment by celanthe** [comment]
@akeller @falko  is there any action item needed from me here? Otherwise, I can un-assign myself from this issue. Thank you!

**Comment by akeller** [comment]
You can unassign yourself. Thanks @celanthe!

**Comment by falko** [comment]
The Docker Compose configurations created by this project have become the official files that are included in the Camunda Platform release. We should now deprecate this project and guide users and contributors to the official product repo: https://github.com/camunda/camunda-platform

Additional documentation that we wrote here should be contributed to:
https://github.com/camunda/camunda-platform/blob/main/README.md
https://github.com/camunda-cloud/camunda-cloud-documentation/blob/master/docs/self-managed/platform-deployment/docker.md
A PR for the docs is already ongoing: https://github.com/camunda-cloud/camunda-cloud-documentation/pull/802

**Comment by akeller** [comment]
Do you want to archive this project or completely delete it? If we archive it, I want to adjust the README to point to the official repo, so that's my recommended path here.

**Comment by superbeagle** [comment]
Let's archive it with an updated readme that points to the official repo just in case somebody comes here through an old link

**Comment by superbeagle** [comment]
I will update tomorrow after I return

**Comment by berndruecker** [comment]
I added a quick deprecation warning (as part of https://github.com/camunda-cloud/camunda-cloud-documentation/issues/812) - hope that's OK!

**Comment by superbeagle** [comment]
Yes, thank you!

**Comment by akeller** [comment]
Fantastic, are we good to archive at this point? Or @superbeagle are you still making updates? Otherwise, I'll close out the two issues and archive the repo.

**Comment by superbeagle** [comment]
Repo will be archived today
